# Generated by Django 4.2.6 on 2023-10-24 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='fichier',
            name='classe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Api.classe'),
            preserve_default=False,
        ),
    ]
